### ISSUE TITLE
Configure ipns-publisher to connect to w3name Websocket endpoints

### ISSUE THREAD

**Issue by adamalton** [web3-storage/ipns-publisher#2]
We're moving the websocket endpoints from being part of web3.storage to being a separate CloudFlare Worker running from the new [w3name repo](https://github.com/web3-storage/w3name).

So we need to update this service to point to the new endpoints on their new domain.

**Comment by mbommerez** [comment]
We'll need to wait until we have the domain name for the PROD w3name APIs.
