### ISSUE TITLE
Add HTTP POST broadcast endpoint

### ISSUE THREAD

**Issue by francois-potato** [web3-storage/ipns-publisher#3]
# Context

w3name need to rebroadcast IPNS request every 24 hours. w3name should be able to POST to `ipns-publisher` to request a rebroadcast to the DHT.

# Scope of this ticket

* Add an HTTP server and request handler, the endpoint should accept JSON and validate the received payload (similar to the payload received by the WebSocket)
*  The endpoint should be available on `/broadcast`

# Acceptance criteria

- [ ] When receiving a POST request on `/broadcast`, the payload is validated and the IPNS record is pushed to the DHT.

**Comment by adamalton** [comment]
Implemented in #4.
